version: '3.8'

services:
  rudra:
    build: 
      context: .
      dockerfile: Dockerfile
    image: adityamaller/rudra:latest
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
