name: DevOps Tests

on:
  push:
  pull_request:

jobs:
  devops-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: '3.10' # Or your target Python version for tests

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Ensure 'docker' and 'requests' are in here if used by tests
          pip install pytest docker requests # Explicitly install

      - name: Run devops tests
        run: |
          pytest test/devops/test_docker_setup.py -v
